[project]
name = "katas"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.8",
]

[tool.ruff.lint]
ignore = [
	"E402", # Module level import not at top of file
	"E741"  # Ambiguous variable name: `l`
]
