name: Running tests with pytest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/astral-sh/uv:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest **/*.py
